### ISSUE TITLE
add permissions policy support for webauthn

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webappsec-credential-management#136]
webauthn has needs to integrate with [Feature Policy](https://www.w3.org/TR/feature-policy/): https://github.com/w3c/webauthn/issues/911 "integrate with feature policy..."

This issue is only to note the above. There are overall questions wrt whether we do credential feature polic{y,ies} as per-credential or all-creds-included: see issue #135.

**Comment by agl** [comment]
On whether to have type-specific controls (i.e. allowing &ldquo;webauthn&rdquo;) or more general controls (i.e. allowing &ldquo;credman&rdquo;):

I think I would favour type-specific controls. Otherwise, if other credentials types were added in the future with different security considerations then there would be friction because of the potential set of sites that have delegated &ldquo;credman&rdquo; powers to iframes, but without having considered whatever new concerns that might arise with future credential types.

**Comment by equalsJeffH** [comment]
Webauthn has been nominally integrated with permissions policy nee feature policy for a while now, so am closing this issue. 

For presently relevant undecided questions wrt permissions policy and Credman, see #135.

**Comment by equalsJeffH** [comment]
Actually, upon further review, nominal changes to Credman in _specific_ support of WebAuthn-cum-Credman's _present_ dependency upon [permissions policy](https://w3c.github.io/webappsec-permissions-policy/) are warranted, so am re-opening this issue.

Note that there are also further presently undecided questions regarding [permissions policy](https://w3c.github.io/webappsec-permissions-policy/) and Credman, see issue #135.

Details:

As noted in WebAuthn for both of PublicKeyCredential’s [`[[Create]]()`](https://www.w3.org/TR/webauthn/#sctn-createCredential) and  [`[[DiscoverFromExternalSource]]()`](https://www.w3.org/TR/webauthn/#sctn-discover-from-external-source) methods:  
> Note: Invocation of this internal method indicates that it was allowed by permissions policy, which is evaluated at the [CREDENTIAL-MANAGEMENT-1] level. [ ... ]

And also noted in WebAuthn's section [5.9. Permissions Policy integration](https://www.w3.org/TR/webauthn/#sctn-permissions-policy):
> Algorithms specified in [CREDENTIAL-MANAGEMENT-1] perform the actual permissions policy evaluation. [ ... ]
