### ISSUE TITLE
Clarify storage of a SiteBoundCredential

### ISSUE THREAD

**Issue by jonathanKingston** [w3c/webappsec-credential-management#28]
In the following step: ["Store SiteBoundCredential"](https://w3c.github.io/webappsec-credential-management/#store-siteboundcredential)

The spec suggests it can accept `SiteBoundCredential`'s but ["Store a Credential"](https://w3c.github.io/webappsec-credential-management/#store-credential) also suggests that types that extend from `SiteBoundCredential` also can be passed into the algo.

For example [PasswordCredential](https://w3c.github.io/webappsec-credential-management/#passwordcredential) permits the use of `AditionalData` and [FederatedCredential](https://w3c.github.io/webappsec-credential-management/#federatedcredential) accepts `provider` and `protocol`.

To me the storage algorithm isn't clear when it is storing this aditional data as I think the following statements are true:
- `FederatedCredential` store `provider` and `protocol` data into the store
- `PasswordCredential` stores `idName`, `passwordName` but **not** `AditionalData` into the store
  - Storing `AditionalData` would lead to the CSRF example replaying that field always
  - Storing files and arbitary amounts of data to the store doesn't seem the goal of the specification

**Comment by jonathanKingston** [comment]
Perhaps an alternative question would be what would https://w3c.github.io/webappsec-credential-management/#request-credential provide in terms of data for each type? Would `idName` and `aditionalData` be populated?

**Comment by vabr-g** [comment]
Thanks for pointing this out.
My guess is that the information stored for PasswordCredential amounts to what is captured in PasswordCredentialData (name + iconUrl from SiteBoundCredentialData and password), and similarly FederatedCredentialData is what is stored for FederatedCredential (name, iconUrl, provider and protocol).

I agree that the spec does not seem to make this clear. While I'll keep looking at it and trying to figure out if there is a better phrasing, perhaps @mikewest can double-check my above claim and add any comments if he has some?

**Comment by mikewest** [comment]
The idea is that the credential store understands a set of credential types, and knows how to store them. We define two such types in this document, and the listing of their properties is exhaustive. I didn't intend the credential store to be a general purpose storage mechanism, given the radically different lifetime guarantees and user mediation requirements.

It's probably worth expanding the definition to spell that out in more detail. I didn't sketch that out in much detail, because the spec can't (and shouldn't) dictate the internals of a particular credential manager, but I think it's probably worth noting that only the persistent fields are actually stored. Drawing a distinction between the fields that make up the credential itself, and the fields which are only used for a single instance of the credential is a totally reasonable thing to do.

**Comment by vabr-g** [comment]
Thanks for the clarification!
When you say "persistent fields", that would be what comes into the *Credential constructors captured inside the *CredentialData objects? Or how would you prefer to define this data?

**Comment by battre** [comment]
I have made a proposal to clarify this.
