### ISSUE TITLE
Should PasswordCredential accept `id` of the form elements if the `name` is missing?

### ISSUE THREAD

**Issue by vabr-g** [w3c/webappsec-credential-management#35]
https://w3c.github.io/webappsec-credential-management/#passwordcredential-form-constructor requires that form input elements have `name` attributes, and derives the credential metadata based on those. It ignores the `id` attribute. In the absence of `name`, could it fall back to accepting `id` as the source for the name in the metadata? (This is what happens in the particular case of Chrome and form-based autofill (see HTMLFormControlElement::nameForAutofill in https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/html/HTMLFormControlElement.cpp?sq=package:chromium&dr=C&rcl=1482394814&l=625-632).

**Comment by mikewest** [comment]
AFAIK, the `id` field isn't used when serializing the form onto the wire. That is:

```
<form action="https://example.com/">
    <input type="text" id="yay" value="boo">
    <input type="submit">
</form>
```

Will cause a GET request to `https://example.com/?`. Replace `id` with `name` in the above code, and you'll see the request to `https://example.com/?yay=boo` that you probably expected.

If the goal is to ensure that we have a reasonable fallback by making such a fallback the simplest way to construct a `Credential`, then I think we need to require `name`. Otherwise we're not ensuring that the fallback actually works.

Autofill's behavior doesn't really make sense to me. Perhaps it's looking at IDs because it actually fills the form, making the data available to JavaScript? *shrug*

**Comment by vabr-g** [comment]
Thanks for the explanation! Being consistent with what is used for GET makes sense to me.

I can also see now that the Chrome autofill's reasons to use the name fields are different. The nearest use-case is when it parses the form to store it; there it indeed stores the field name-or-ID just to be able to fill it in again. This might be changed soon, however, and is not very related to what CM API uses the name for.

Therefore, all seems OK with the spec in this respect. Thanks for clarifying this for me.
